using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core
{
    /// <summary>
    /// This model is the model for all the users of the chat. 
    /// </summary>
    public class User
    {
        //identifier of the user
        public string Id { get; set; }
        //name of the user
        public string Name { get; set; }
        //public key generated by the user, and shared
        public string PublicKey { get; set; }
        //If this user is the local user
        public bool LocalUser { get; set; }
        //only if it's the current user, we don't want others to have our private key
        public string PrivateKey { get; set; }
    }
}
